# Sidebar navigation

- label: 'Prework'
  link: '/'
- label: HTML
  items:
    - label: 'Contents'
      link: '/html#contents'
    - label: 'HTML Section project'
      link: '/html#html-section-projects'
    - label: 'Further reading'
      link: '/html#further-reading'
