# Sidebar navigation

- label: 'Prework'
  items:
    - label: 'Introduction'
      link: '/prework/introduction'
    - label: 'Contents'
      link: '/prework/contents'
    - label: 'Prework test'
      link: '/prework/prework-test'
    - label: 'Further reading'
      link: '/prework/further-reading'
- label: 'Git'
  items:
    - label: 'Introduction'
      link: '/git/introduction'
    - label: 'Contents'
      link: '/git/contents'
    - label: 'Further reading'
      link: '/git/further-reading'
- label: HTML
  items:
    - label: 'Introduction'
      link: '/html/introduction'
    - label: 'Contents'
      link: '/html/contents'
    - label: 'HTML Section project'
      link: '/html/html-section-project'
    - label: 'Further reading'
      link: '/html/further-reading'
- label: CSS
  items:
    - label: 'Introduction'
      link: '/css/introduction'
    - label: 'Contents'
      link: '/css/contents'
    - label: 'CSS Section project'
      link: '/css/css-section-project'
    - label: 'Further reading'
      link: '/css/further-reading'
- label: SASS
  items:
    - label: 'Introduction'
      link: '/sass/introduction'
    - label: 'Contents'
      link: '/sass/contents'
    - label: 'Further reading'
      link: '/sass/further-reading'
- label: Basic Javascript
  items:
    - label: 'Introduction'
      link: '/basic-js/introduction'
    - label: 'Contents'
      link: '/basic-js/contents'
    - label: 'Basic JS Section project'
      link: '/basic-js/basic-js-section-project'
    - label: 'Further reading'
      link: '/basic-js/further-reading'
